export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_DRIVERS = 'GET_USER_DRIVERS';
export const DRIVERS_RECEIVED = 'DRIVERS_RECEIVED';
export const REQUEST_NEW_DRIVER_ADD = 'REQUEST_NEW_DRIVER_ADD';
export const DRIVER_ADD_ERROR = 'DRIVER_ADD_ERROR';
export const REQUEST_DELETE_DRIVER = 'REQUEST_DELETE_DRIVER';
